### ISSUE TITLE
Clone or Download button link has a . at the end which should not be there

### ISSUE THREAD

**Issue by zanco** [pothosware/SoapyRTLSDR#27]
When using the copy button to clone the url one "dot" is on the end of the url, which makes git asking for a usernamer.

After removing the 'dot' at the end of the url all works ok.

Cheers,

Ben

**Comment by guruofquality** [comment]
So what did the url look like when you copied it? This is a github standard thing, so we dont have much control over it.

I suspect that you copied part of the url because it was cutoff by the width of the box. Surprisingly if you remove the ".git" from the url the clone still works.

So make sure you select "clone with https" and copy the entire url "https://github.com/pothosware/SoapyRTLSDR.git".
